"""Module with all the book info for the NLT"""
books = [{'chapters': [{'file': 'Gen_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x1genesis_1.html', 'title': '1'},
               {'file': 'x1genesis_2.html', 'title': '2'},
               {'file': 'x1genesis_3.html', 'title': '3'},
               {'file': 'x1genesis_4.html', 'title': '4'},
               {'file': 'x1genesis_5.html', 'title': '5'},
               {'file': 'x1genesis_6.html', 'title': '6'},
               {'file': 'x1genesis_7.html', 'title': '7'},
               {'file': 'x1genesis_8.html', 'title': '8'},
               {'file': 'x1genesis_9.html', 'title': '9'},
               {'file': 'x1genesis_10.html', 'title': '10'},
               {'file': 'x1genesis_11.html', 'title': '11'},
               {'file': 'x1genesis_12.html', 'title': '12'},
               {'file': 'x1genesis_13.html', 'title': '13'},
               {'file': 'x1genesis_14.html', 'title': '14'},
               {'file': 'x1genesis_15.html', 'title': '15'},
               {'file': 'x1genesis_16.html', 'title': '16'},
               {'file': 'x1genesis_17.html', 'title': '17'},
               {'file': 'x1genesis_18.html', 'title': '18'},
               {'file': 'x1genesis_19.html', 'title': '19'},
               {'file': 'x1genesis_20.html', 'title': '20'},
               {'file': 'x1genesis_21.html', 'title': '21'},
               {'file': 'x1genesis_22.html', 'title': '22'},
               {'file': 'x1genesis_23.html', 'title': '23'},
               {'file': 'x1genesis_24.html', 'title': '24'},
               {'file': 'x1genesis_25.html', 'title': '25'},
               {'file': 'x1genesis_26.html', 'title': '26'},
               {'file': 'x1genesis_27.html', 'title': '27'},
               {'file': 'x1genesis_28.html', 'title': '28'},
               {'file': 'x1genesis_29.html', 'title': '29'},
               {'file': 'x1genesis_30.html', 'title': '30'},
               {'file': 'x1genesis_31.html', 'title': '31'},
               {'file': 'x1genesis_32.html', 'title': '32'},
               {'file': 'x1genesis_33.html', 'title': '33'},
               {'file': 'x1genesis_34.html', 'title': '34'},
               {'file': 'x1genesis_35.html', 'title': '35'},
               {'file': 'x1genesis_36.html', 'title': '36'},
               {'file': 'x1genesis_37.html', 'title': '37'},
               {'file': 'x1genesis_38.html', 'title': '38'},
               {'file': 'x1genesis_39.html', 'title': '39'},
               {'file': 'x1genesis_40.html', 'title': '40'},
               {'file': 'x1genesis_41.html', 'title': '41'},
               {'file': 'x1genesis_42.html', 'title': '42'},
               {'file': 'x1genesis_43.html', 'title': '43'},
               {'file': 'x1genesis_44.html', 'title': '44'},
               {'file': 'x1genesis_45.html', 'title': '45'},
               {'file': 'x1genesis_46.html', 'title': '46'},
               {'file': 'x1genesis_47.html', 'title': '47'},
               {'file': 'x1genesis_48.html', 'title': '48'},
               {'file': 'x1genesis_49.html', 'title': '49'},
               {'file': 'x1genesis_50.html', 'title': '50'}],
  'long': 'Genesis',
  'short': 'GEN',
  'testament': 'Old',
  'tocfile': 'x1genesis.html'},
 {'chapters': [{'file': 'Exod_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x2exodus_1.html', 'title': '1'},
               {'file': 'x2exodus_2.html', 'title': '2'},
               {'file': 'x2exodus_3.html', 'title': '3'},
               {'file': 'x2exodus_4.html', 'title': '4'},
               {'file': 'x2exodus_5.html', 'title': '5'},
               {'file': 'x2exodus_6.html', 'title': '6'},
               {'file': 'x2exodus_7.html', 'title': '7'},
               {'file': 'x2exodus_8.html', 'title': '8'},
               {'file': 'x2exodus_9.html', 'title': '9'},
               {'file': 'x2exodus_10.html', 'title': '10'},
               {'file': 'x2exodus_11.html', 'title': '11'},
               {'file': 'x2exodus_12.html', 'title': '12'},
               {'file': 'x2exodus_13.html', 'title': '13'},
               {'file': 'x2exodus_14.html', 'title': '14'},
               {'file': 'x2exodus_15.html', 'title': '15'},
               {'file': 'x2exodus_16.html', 'title': '16'},
               {'file': 'x2exodus_17.html', 'title': '17'},
               {'file': 'x2exodus_18.html', 'title': '18'},
               {'file': 'x2exodus_19.html', 'title': '19'},
               {'file': 'x2exodus_20.html', 'title': '20'},
               {'file': 'x2exodus_21.html', 'title': '21'},
               {'file': 'x2exodus_22.html', 'title': '22'},
               {'file': 'x2exodus_23.html', 'title': '23'},
               {'file': 'x2exodus_24.html', 'title': '24'},
               {'file': 'x2exodus_25.html', 'title': '25'},
               {'file': 'x2exodus_26.html', 'title': '26'},
               {'file': 'x2exodus_27.html', 'title': '27'},
               {'file': 'x2exodus_28.html', 'title': '28'},
               {'file': 'x2exodus_29.html', 'title': '29'},
               {'file': 'x2exodus_30.html', 'title': '30'},
               {'file': 'x2exodus_31.html', 'title': '31'},
               {'file': 'x2exodus_32.html', 'title': '32'},
               {'file': 'x2exodus_33.html', 'title': '33'},
               {'file': 'x2exodus_34.html', 'title': '34'},
               {'file': 'x2exodus_35.html', 'title': '35'},
               {'file': 'x2exodus_36.html', 'title': '36'},
               {'file': 'x2exodus_37.html', 'title': '37'},
               {'file': 'x2exodus_38.html', 'title': '38'},
               {'file': 'x2exodus_39.html', 'title': '39'},
               {'file': 'x2exodus_40.html', 'title': '40'}],
  'long': 'Exodus',
  'short': 'EXO',
  'testament': 'Old',
  'tocfile': 'x2exodus.html'},
 {'chapters': [{'file': 'Lev_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x3leviticus_1.html', 'title': '1'},
               {'file': 'x3leviticus_2.html', 'title': '2'},
               {'file': 'x3leviticus_3.html', 'title': '3'},
               {'file': 'x3leviticus_4.html', 'title': '4'},
               {'file': 'x3leviticus_5.html', 'title': '5'},
               {'file': 'x3leviticus_6.html', 'title': '6'},
               {'file': 'x3leviticus_7.html', 'title': '7'},
               {'file': 'x3leviticus_8.html', 'title': '8'},
               {'file': 'x3leviticus_9.html', 'title': '9'},
               {'file': 'x3leviticus_10.html', 'title': '10'},
               {'file': 'x3leviticus_11.html', 'title': '11'},
               {'file': 'x3leviticus_12.html', 'title': '12'},
               {'file': 'x3leviticus_13.html', 'title': '13'},
               {'file': 'x3leviticus_14.html', 'title': '14'},
               {'file': 'x3leviticus_15.html', 'title': '15'},
               {'file': 'x3leviticus_16.html', 'title': '16'},
               {'file': 'x3leviticus_17.html', 'title': '17'},
               {'file': 'x3leviticus_18.html', 'title': '18'},
               {'file': 'x3leviticus_19.html', 'title': '19'},
               {'file': 'x3leviticus_20.html', 'title': '20'},
               {'file': 'x3leviticus_21.html', 'title': '21'},
               {'file': 'x3leviticus_22.html', 'title': '22'},
               {'file': 'x3leviticus_23.html', 'title': '23'},
               {'file': 'x3leviticus_24.html', 'title': '24'},
               {'file': 'x3leviticus_25.html', 'title': '25'},
               {'file': 'x3leviticus_26.html', 'title': '26'},
               {'file': 'x3leviticus_27.html', 'title': '27'}],
  'long': 'Leviticus',
  'short': 'LEV',
  'testament': 'Old',
  'tocfile': 'x3leviticus.html'},
 {'chapters': [{'file': 'Num_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x4numbers_1.html', 'title': '1'},
               {'file': 'x4numbers_2.html', 'title': '2'},
               {'file': 'x4numbers_3.html', 'title': '3'},
               {'file': 'x4numbers_4.html', 'title': '4'},
               {'file': 'x4numbers_5.html', 'title': '5'},
               {'file': 'x4numbers_6.html', 'title': '6'},
               {'file': 'x4numbers_7.html', 'title': '7'},
               {'file': 'x4numbers_8.html', 'title': '8'},
               {'file': 'x4numbers_9.html', 'title': '9'},
               {'file': 'x4numbers_10.html', 'title': '10'},
               {'file': 'x4numbers_11.html', 'title': '11'},
               {'file': 'x4numbers_12.html', 'title': '12'},
               {'file': 'x4numbers_13.html', 'title': '13'},
               {'file': 'x4numbers_14.html', 'title': '14'},
               {'file': 'x4numbers_15.html', 'title': '15'},
               {'file': 'x4numbers_16.html', 'title': '16'},
               {'file': 'x4numbers_17.html', 'title': '17'},
               {'file': 'x4numbers_18.html', 'title': '18'},
               {'file': 'x4numbers_19.html', 'title': '19'},
               {'file': 'x4numbers_20.html', 'title': '20'},
               {'file': 'x4numbers_21.html', 'title': '21'},
               {'file': 'x4numbers_22.html', 'title': '22'},
               {'file': 'x4numbers_23.html', 'title': '23'},
               {'file': 'x4numbers_24.html', 'title': '24'},
               {'file': 'x4numbers_25.html', 'title': '25'},
               {'file': 'x4numbers_26.html', 'title': '26'},
               {'file': 'x4numbers_27.html', 'title': '27'},
               {'file': 'x4numbers_28.html', 'title': '28'},
               {'file': 'x4numbers_29.html', 'title': '29'},
               {'file': 'x4numbers_30.html', 'title': '30'},
               {'file': 'x4numbers_31.html', 'title': '31'},
               {'file': 'x4numbers_32.html', 'title': '32'},
               {'file': 'x4numbers_33.html', 'title': '33'},
               {'file': 'x4numbers_34.html', 'title': '34'},
               {'file': 'x4numbers_35.html', 'title': '35'},
               {'file': 'x4numbers_36.html', 'title': '36'}],
  'long': 'Numbers',
  'short': 'NUM',
  'testament': 'Old',
  'tocfile': 'x4numbers.html'},
 {'chapters': [{'file': 'Deut_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x5deuteronomy_1.html', 'title': '1'},
               {'file': 'x5deuteronomy_2.html', 'title': '2'},
               {'file': 'x5deuteronomy_3.html', 'title': '3'},
               {'file': 'x5deuteronomy_4.html', 'title': '4'},
               {'file': 'x5deuteronomy_5.html', 'title': '5'},
               {'file': 'x5deuteronomy_6.html', 'title': '6'},
               {'file': 'x5deuteronomy_7.html', 'title': '7'},
               {'file': 'x5deuteronomy_8.html', 'title': '8'},
               {'file': 'x5deuteronomy_9.html', 'title': '9'},
               {'file': 'x5deuteronomy_10.html', 'title': '10'},
               {'file': 'x5deuteronomy_11.html', 'title': '11'},
               {'file': 'x5deuteronomy_12.html', 'title': '12'},
               {'file': 'x5deuteronomy_13.html', 'title': '13'},
               {'file': 'x5deuteronomy_14.html', 'title': '14'},
               {'file': 'x5deuteronomy_15.html', 'title': '15'},
               {'file': 'x5deuteronomy_16.html', 'title': '16'},
               {'file': 'x5deuteronomy_17.html', 'title': '17'},
               {'file': 'x5deuteronomy_18.html', 'title': '18'},
               {'file': 'x5deuteronomy_19.html', 'title': '19'},
               {'file': 'x5deuteronomy_20.html', 'title': '20'},
               {'file': 'x5deuteronomy_21.html', 'title': '21'},
               {'file': 'x5deuteronomy_22.html', 'title': '22'},
               {'file': 'x5deuteronomy_23.html', 'title': '23'},
               {'file': 'x5deuteronomy_24.html', 'title': '24'},
               {'file': 'x5deuteronomy_25.html', 'title': '25'},
               {'file': 'x5deuteronomy_26.html', 'title': '26'},
               {'file': 'x5deuteronomy_27.html', 'title': '27'},
               {'file': 'x5deuteronomy_28.html', 'title': '28'},
               {'file': 'x5deuteronomy_29.html', 'title': '29'},
               {'file': 'x5deuteronomy_30.html', 'title': '30'},
               {'file': 'x5deuteronomy_31.html', 'title': '31'},
               {'file': 'x5deuteronomy_32.html', 'title': '32'},
               {'file': 'x5deuteronomy_33.html', 'title': '33'},
               {'file': 'x5deuteronomy_34.html', 'title': '34'}],
  'long': 'Deuteronomy',
  'short': 'DEU',
  'testament': 'Old',
  'tocfile': 'x5deuteronomy.html'},
 {'chapters': [{'file': 'Josh_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x6joshua_1.html', 'title': '1'},
               {'file': 'x6joshua_2.html', 'title': '2'},
               {'file': 'x6joshua_3.html', 'title': '3'},
               {'file': 'x6joshua_4.html', 'title': '4'},
               {'file': 'x6joshua_5.html', 'title': '5'},
               {'file': 'x6joshua_6.html', 'title': '6'},
               {'file': 'x6joshua_7.html', 'title': '7'},
               {'file': 'x6joshua_8.html', 'title': '8'},
               {'file': 'x6joshua_9.html', 'title': '9'},
               {'file': 'x6joshua_10.html', 'title': '10'},
               {'file': 'x6joshua_11.html', 'title': '11'},
               {'file': 'x6joshua_12.html', 'title': '12'},
               {'file': 'x6joshua_13.html', 'title': '13'},
               {'file': 'x6joshua_14.html', 'title': '14'},
               {'file': 'x6joshua_15.html', 'title': '15'},
               {'file': 'x6joshua_16.html', 'title': '16'},
               {'file': 'x6joshua_17.html', 'title': '17'},
               {'file': 'x6joshua_18.html', 'title': '18'},
               {'file': 'x6joshua_19.html', 'title': '19'},
               {'file': 'x6joshua_20.html', 'title': '20'},
               {'file': 'x6joshua_21.html', 'title': '21'},
               {'file': 'x6joshua_22.html', 'title': '22'},
               {'file': 'x6joshua_23.html', 'title': '23'},
               {'file': 'x6joshua_24.html', 'title': '24'}],
  'long': 'Joshua',
  'short': 'JOS',
  'testament': 'Old',
  'tocfile': 'x6joshua.html'},
 {'chapters': [{'file': 'Judg_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x7judges_1.html', 'title': '1'},
               {'file': 'x7judges_2.html', 'title': '2'},
               {'file': 'x7judges_3.html', 'title': '3'},
               {'file': 'x7judges_4.html', 'title': '4'},
               {'file': 'x7judges_5.html', 'title': '5'},
               {'file': 'x7judges_6.html', 'title': '6'},
               {'file': 'x7judges_7.html', 'title': '7'},
               {'file': 'x7judges_8.html', 'title': '8'},
               {'file': 'x7judges_9.html', 'title': '9'},
               {'file': 'x7judges_10.html', 'title': '10'},
               {'file': 'x7judges_11.html', 'title': '11'},
               {'file': 'x7judges_12.html', 'title': '12'},
               {'file': 'x7judges_13.html', 'title': '13'},
               {'file': 'x7judges_14.html', 'title': '14'},
               {'file': 'x7judges_15.html', 'title': '15'},
               {'file': 'x7judges_16.html', 'title': '16'},
               {'file': 'x7judges_17.html', 'title': '17'},
               {'file': 'x7judges_18.html', 'title': '18'},
               {'file': 'x7judges_19.html', 'title': '19'},
               {'file': 'x7judges_20.html', 'title': '20'},
               {'file': 'x7judges_21.html', 'title': '21'}],
  'long': 'Judges',
  'short': 'JDG',
  'testament': 'Old',
  'tocfile': 'x7judges.html'},
 {'chapters': [{'file': 'Ruth_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x8ruth_1.html', 'title': '1'},
               {'file': 'x8ruth_2.html', 'title': '2'},
               {'file': 'x8ruth_3.html', 'title': '3'},
               {'file': 'x8ruth_4.html', 'title': '4'}],
  'long': 'Ruth',
  'short': 'RUT',
  'testament': 'Old',
  'tocfile': 'x8ruth.html'},
 {'chapters': [{'file': 'ISam_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x91samuel_1.html', 'title': '1'},
               {'file': 'x91samuel_2.html', 'title': '2'},
               {'file': 'x91samuel_3.html', 'title': '3'},
               {'file': 'x91samuel_4.html', 'title': '4'},
               {'file': 'x91samuel_5.html', 'title': '5'},
               {'file': 'x91samuel_6.html', 'title': '6'},
               {'file': 'x91samuel_7.html', 'title': '7'},
               {'file': 'x91samuel_8.html', 'title': '8'},
               {'file': 'x91samuel_9.html', 'title': '9'},
               {'file': 'x91samuel_10.html', 'title': '10'},
               {'file': 'x91samuel_11.html', 'title': '11'},
               {'file': 'x91samuel_12.html', 'title': '12'},
               {'file': 'x91samuel_13.html', 'title': '13'},
               {'file': 'x91samuel_14.html', 'title': '14'},
               {'file': 'x91samuel_15.html', 'title': '15'},
               {'file': 'x91samuel_16.html', 'title': '16'},
               {'file': 'x91samuel_17.html', 'title': '17'},
               {'file': 'x91samuel_18.html', 'title': '18'},
               {'file': 'x91samuel_19.html', 'title': '19'},
               {'file': 'x91samuel_20.html', 'title': '20'},
               {'file': 'x91samuel_21.html', 'title': '21'},
               {'file': 'x91samuel_22.html', 'title': '22'},
               {'file': 'x91samuel_23.html', 'title': '23'},
               {'file': 'x91samuel_24.html', 'title': '24'},
               {'file': 'x91samuel_25.html', 'title': '25'},
               {'file': 'x91samuel_26.html', 'title': '26'},
               {'file': 'x91samuel_27.html', 'title': '27'},
               {'file': 'x91samuel_28.html', 'title': '28'},
               {'file': 'x91samuel_29.html', 'title': '29'},
               {'file': 'x91samuel_30.html', 'title': '30'},
               {'file': 'x91samuel_31.html', 'title': '31'}],
  'long': '1 Samuel',
  'short': '1SA',
  'testament': 'Old',
  'tocfile': 'x91samuel.html'},
 {'chapters': [{'file': 'IISam_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x102samuel_1.html', 'title': '1'},
               {'file': 'x102samuel_2.html', 'title': '2'},
               {'file': 'x102samuel_3.html', 'title': '3'},
               {'file': 'x102samuel_4.html', 'title': '4'},
               {'file': 'x102samuel_5.html', 'title': '5'},
               {'file': 'x102samuel_6.html', 'title': '6'},
               {'file': 'x102samuel_7.html', 'title': '7'},
               {'file': 'x102samuel_8.html', 'title': '8'},
               {'file': 'x102samuel_9.html', 'title': '9'},
               {'file': 'x102samuel_10.html', 'title': '10'},
               {'file': 'x102samuel_11.html', 'title': '11'},
               {'file': 'x102samuel_12.html', 'title': '12'},
               {'file': 'x102samuel_13.html', 'title': '13'},
               {'file': 'x102samuel_14.html', 'title': '14'},
               {'file': 'x102samuel_15.html', 'title': '15'},
               {'file': 'x102samuel_16.html', 'title': '16'},
               {'file': 'x102samuel_17.html', 'title': '17'},
               {'file': 'x102samuel_18.html', 'title': '18'},
               {'file': 'x102samuel_19.html', 'title': '19'},
               {'file': 'x102samuel_20.html', 'title': '20'},
               {'file': 'x102samuel_21.html', 'title': '21'},
               {'file': 'x102samuel_22.html', 'title': '22'},
               {'file': 'x102samuel_23.html', 'title': '23'},
               {'file': 'x102samuel_24.html', 'title': '24'}],
  'long': '2 Samuel',
  'short': '2SA',
  'testament': 'Old',
  'tocfile': 'x102samuel.html'},
 {'chapters': [{'file': 'IKgs_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x111kings_1.html', 'title': '1'},
               {'file': 'x111kings_2.html', 'title': '2'},
               {'file': 'x111kings_3.html', 'title': '3'},
               {'file': 'x111kings_4.html', 'title': '4'},
               {'file': 'x111kings_5.html', 'title': '5'},
               {'file': 'x111kings_6.html', 'title': '6'},
               {'file': 'x111kings_7.html', 'title': '7'},
               {'file': 'x111kings_8.html', 'title': '8'},
               {'file': 'x111kings_9.html', 'title': '9'},
               {'file': 'x111kings_10.html', 'title': '10'},
               {'file': 'x111kings_11.html', 'title': '11'},
               {'file': 'x111kings_12.html', 'title': '12'},
               {'file': 'x111kings_13.html', 'title': '13'},
               {'file': 'x111kings_14.html', 'title': '14'},
               {'file': 'x111kings_15.html', 'title': '15'},
               {'file': 'x111kings_16.html', 'title': '16'},
               {'file': 'x111kings_17.html', 'title': '17'},
               {'file': 'x111kings_18.html', 'title': '18'},
               {'file': 'x111kings_19.html', 'title': '19'},
               {'file': 'x111kings_20.html', 'title': '20'},
               {'file': 'x111kings_21.html', 'title': '21'},
               {'file': 'x111kings_22.html', 'title': '22'}],
  'long': '1 Kings',
  'short': '1KI',
  'testament': 'Old',
  'tocfile': 'x111kings.html'},
 {'chapters': [{'file': 'IIKgs_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x122kings_1.html', 'title': '1'},
               {'file': 'x122kings_2.html', 'title': '2'},
               {'file': 'x122kings_3.html', 'title': '3'},
               {'file': 'x122kings_4.html', 'title': '4'},
               {'file': 'x122kings_5.html', 'title': '5'},
               {'file': 'x122kings_6.html', 'title': '6'},
               {'file': 'x122kings_7.html', 'title': '7'},
               {'file': 'x122kings_8.html', 'title': '8'},
               {'file': 'x122kings_9.html', 'title': '9'},
               {'file': 'x122kings_10.html', 'title': '10'},
               {'file': 'x122kings_11.html', 'title': '11'},
               {'file': 'x122kings_12.html', 'title': '12'},
               {'file': 'x122kings_13.html', 'title': '13'},
               {'file': 'x122kings_14.html', 'title': '14'},
               {'file': 'x122kings_15.html', 'title': '15'},
               {'file': 'x122kings_16.html', 'title': '16'},
               {'file': 'x122kings_17.html', 'title': '17'},
               {'file': 'x122kings_18.html', 'title': '18'},
               {'file': 'x122kings_19.html', 'title': '19'},
               {'file': 'x122kings_20.html', 'title': '20'},
               {'file': 'x122kings_21.html', 'title': '21'},
               {'file': 'x122kings_22.html', 'title': '22'},
               {'file': 'x122kings_23.html', 'title': '23'},
               {'file': 'x122kings_24.html', 'title': '24'},
               {'file': 'x122kings_25.html', 'title': '25'}],
  'long': '2 Kings',
  'short': '2KI',
  'testament': 'Old',
  'tocfile': 'x122kings.html'},
 {'chapters': [{'file': 'IChr_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x131chronicles_1.html', 'title': '1'},
               {'file': 'x131chronicles_2.html', 'title': '2'},
               {'file': 'x131chronicles_3.html', 'title': '3'},
               {'file': 'x131chronicles_4.html', 'title': '4'},
               {'file': 'x131chronicles_5.html', 'title': '5'},
               {'file': 'x131chronicles_6.html', 'title': '6'},
               {'file': 'x131chronicles_7.html', 'title': '7'},
               {'file': 'x131chronicles_8.html', 'title': '8'},
               {'file': 'x131chronicles_9.html', 'title': '9'},
               {'file': 'x131chronicles_10.html', 'title': '10'},
               {'file': 'x131chronicles_11.html', 'title': '11'},
               {'file': 'x131chronicles_12.html', 'title': '12'},
               {'file': 'x131chronicles_13.html', 'title': '13'},
               {'file': 'x131chronicles_14.html', 'title': '14'},
               {'file': 'x131chronicles_15.html', 'title': '15'},
               {'file': 'x131chronicles_16.html', 'title': '16'},
               {'file': 'x131chronicles_17.html', 'title': '17'},
               {'file': 'x131chronicles_18.html', 'title': '18'},
               {'file': 'x131chronicles_19.html', 'title': '19'},
               {'file': 'x131chronicles_20.html', 'title': '20'},
               {'file': 'x131chronicles_21.html', 'title': '21'},
               {'file': 'x131chronicles_22.html', 'title': '22'},
               {'file': 'x131chronicles_23.html', 'title': '23'},
               {'file': 'x131chronicles_24.html', 'title': '24'},
               {'file': 'x131chronicles_25.html', 'title': '25'},
               {'file': 'x131chronicles_26.html', 'title': '26'},
               {'file': 'x131chronicles_27.html', 'title': '27'},
               {'file': 'x131chronicles_28.html', 'title': '28'},
               {'file': 'x131chronicles_29.html', 'title': '29'}],
  'long': '1 Chronicles',
  'short': '1CH',
  'testament': 'Old',
  'tocfile': 'x131chronicles.html'},
 {'chapters': [{'file': 'IIChr_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x142chronicles_1.html', 'title': '1'},
               {'file': 'x142chronicles_2.html', 'title': '2'},
               {'file': 'x142chronicles_3.html', 'title': '3'},
               {'file': 'x142chronicles_4.html', 'title': '4'},
               {'file': 'x142chronicles_5.html', 'title': '5'},
               {'file': 'x142chronicles_6.html', 'title': '6'},
               {'file': 'x142chronicles_7.html', 'title': '7'},
               {'file': 'x142chronicles_8.html', 'title': '8'},
               {'file': 'x142chronicles_9.html', 'title': '9'},
               {'file': 'x142chronicles_10.html', 'title': '10'},
               {'file': 'x142chronicles_11.html', 'title': '11'},
               {'file': 'x142chronicles_12.html', 'title': '12'},
               {'file': 'x142chronicles_13.html', 'title': '13'},
               {'file': 'x142chronicles_14.html', 'title': '14'},
               {'file': 'x142chronicles_15.html', 'title': '15'},
               {'file': 'x142chronicles_16.html', 'title': '16'},
               {'file': 'x142chronicles_17.html', 'title': '17'},
               {'file': 'x142chronicles_18.html', 'title': '18'},
               {'file': 'x142chronicles_19.html', 'title': '19'},
               {'file': 'x142chronicles_20.html', 'title': '20'},
               {'file': 'x142chronicles_21.html', 'title': '21'},
               {'file': 'x142chronicles_22.html', 'title': '22'},
               {'file': 'x142chronicles_23.html', 'title': '23'},
               {'file': 'x142chronicles_24.html', 'title': '24'},
               {'file': 'x142chronicles_25.html', 'title': '25'},
               {'file': 'x142chronicles_26.html', 'title': '26'},
               {'file': 'x142chronicles_27.html', 'title': '27'},
               {'file': 'x142chronicles_28.html', 'title': '28'},
               {'file': 'x142chronicles_29.html', 'title': '29'},
               {'file': 'x142chronicles_30.html', 'title': '30'},
               {'file': 'x142chronicles_31.html', 'title': '31'},
               {'file': 'x142chronicles_32.html', 'title': '32'},
               {'file': 'x142chronicles_33.html', 'title': '33'},
               {'file': 'x142chronicles_34.html', 'title': '34'},
               {'file': 'x142chronicles_35.html', 'title': '35'},
               {'file': 'x142chronicles_36.html', 'title': '36'}],
  'long': '2 Chronicles',
  'short': '2CH',
  'testament': 'Old',
  'tocfile': 'x142chronicles.html'},
 {'chapters': [{'file': 'Ezra_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x15ezra_1.html', 'title': '1'},
               {'file': 'x15ezra_2.html', 'title': '2'},
               {'file': 'x15ezra_3.html', 'title': '3'},
               {'file': 'x15ezra_4.html', 'title': '4'},
               {'file': 'x15ezra_5.html', 'title': '5'},
               {'file': 'x15ezra_6.html', 'title': '6'},
               {'file': 'x15ezra_7.html', 'title': '7'},
               {'file': 'x15ezra_8.html', 'title': '8'},
               {'file': 'x15ezra_9.html', 'title': '9'},
               {'file': 'x15ezra_10.html', 'title': '10'}],
  'long': 'Ezra',
  'short': 'EZR',
  'testament': 'Old',
  'tocfile': 'x15ezra.html'},
 {'chapters': [{'file': 'Neh_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x16nehemiah_1.html', 'title': '1'},
               {'file': 'x16nehemiah_2.html', 'title': '2'},
               {'file': 'x16nehemiah_3.html', 'title': '3'},
               {'file': 'x16nehemiah_4.html', 'title': '4'},
               {'file': 'x16nehemiah_5.html', 'title': '5'},
               {'file': 'x16nehemiah_6.html', 'title': '6'},
               {'file': 'x16nehemiah_7.html', 'title': '7'},
               {'file': 'x16nehemiah_8.html', 'title': '8'},
               {'file': 'x16nehemiah_9.html', 'title': '9'},
               {'file': 'x16nehemiah_10.html', 'title': '10'},
               {'file': 'x16nehemiah_11.html', 'title': '11'},
               {'file': 'x16nehemiah_12.html', 'title': '12'},
               {'file': 'x16nehemiah_13.html', 'title': '13'}],
  'long': 'Nehemiah',
  'short': 'NEH',
  'testament': 'Old',
  'tocfile': 'x16nehemiah.html'},
 {'chapters': [{'file': 'Tob_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x16btobit_1.html', 'title': '1'},
               {'file': 'x16btobit_2.html', 'title': '2'},
               {'file': 'x16btobit_3.html', 'title': '3'},
               {'file': 'x16btobit_4.html', 'title': '4'},
               {'file': 'x16btobit_5.html', 'title': '5'},
               {'file': 'x16btobit_6.html', 'title': '6'},
               {'file': 'x16btobit_7.html', 'title': '7'},
               {'file': 'x16btobit_8.html', 'title': '8'},
               {'file': 'x16btobit_9.html', 'title': '9'},
               {'file': 'x16btobit_10.html', 'title': '10'},
               {'file': 'x16btobit_11.html', 'title': '11'},
               {'file': 'x16btobit_12.html', 'title': '12'},
               {'file': 'x16btobit_13.html', 'title': '13'},
               {'file': 'x16btobit_14.html', 'title': '14'}],
  'long': 'Tobit',
  'short': 'TOB',
  'testament': 'Apocrypha',
  'tocfile': 'x16btobit.html'},
 {'chapters': [{'file': 'Jdt_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x16cjudith_1.html', 'title': '1'},
               {'file': 'x16cjudith_2.html', 'title': '2'},
               {'file': 'x16cjudith_3.html', 'title': '3'},
               {'file': 'x16cjudith_4.html', 'title': '4'},
               {'file': 'x16cjudith_5.html', 'title': '5'},
               {'file': 'x16cjudith_6.html', 'title': '6'},
               {'file': 'x16cjudith_7.html', 'title': '7'},
               {'file': 'x16cjudith_8.html', 'title': '8'},
               {'file': 'x16cjudith_9.html', 'title': '9'},
               {'file': 'x16cjudith_10.html', 'title': '10'},
               {'file': 'x16cjudith_11.html', 'title': '11'},
               {'file': 'x16cjudith_12.html', 'title': '12'},
               {'file': 'x16cjudith_13.html', 'title': '13'},
               {'file': 'x16cjudith_14.html', 'title': '14'},
               {'file': 'x16cjudith_15.html', 'title': '15'},
               {'file': 'x16cjudith_16.html', 'title': '16'}],
  'long': 'Judith',
  'short': 'JDT',
  'testament': 'Apocrypha',
  'tocfile': 'x16cjudith.html'},
 {'chapters': [{'file': 'Esth_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x17besther_a.html', 'title': 'A'},
               {'file': 'x17besther_1.html', 'title': '1'},
               {'file': 'x17besther_2.html', 'title': '2'},
               {'file': 'x17besther_3.html', 'title': '3'},
               {'file': 'x17besther_b.html', 'title': 'B'},
               {'file': 'x17besther_3cont.html', 'title': '3 (continued)'},
               {'file': 'x17besther_4.html', 'title': '4'},
               {'file': 'x17besther_c.html', 'title': 'C'},
               {'file': 'x17besther_d.html', 'title': 'D'},
               {'file': 'x17besther_5.html', 'title': '5'},
               {'file': 'x17besther_6.html', 'title': '6'},
               {'file': 'x17besther_7.html', 'title': '7'},
               {'file': 'x17besther_8.html', 'title': '8'},
               {'file': 'x17besther_e.html', 'title': 'E'},
               {'file': 'x17besther_8cont.html', 'title': '8 (continued)'},
               {'file': 'x17besther_9.html', 'title': '9'},
               {'file': 'x17besther_10.html', 'title': '10'},
               {'file': 'x17besther_f.html', 'title': 'F'}],
  'long': 'Esther',
  'short': 'EST',
  'testament': 'Old',
  'tocfile': 'x17besther.html'},
 {'chapters': [{'file': 'IMacc_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x17c1maccabees_1.html', 'title': '1'},
               {'file': 'x17c1maccabees_2.html', 'title': '2'},
               {'file': 'x17c1maccabees_3.html', 'title': '3'},
               {'file': 'x17c1maccabees_4.html', 'title': '4'},
               {'file': 'x17c1maccabees_5.html', 'title': '5'},
               {'file': 'x17c1maccabees_6.html', 'title': '6'},
               {'file': 'x17c1maccabees_7.html', 'title': '7'},
               {'file': 'x17c1maccabees_8.html', 'title': '8'},
               {'file': 'x17c1maccabees_9.html', 'title': '9'},
               {'file': 'x17c1maccabees_10.html', 'title': '10'},
               {'file': 'x17c1maccabees_11.html', 'title': '11'},
               {'file': 'x17c1maccabees_12.html', 'title': '12'},
               {'file': 'x17c1maccabees_13.html', 'title': '13'},
               {'file': 'x17c1maccabees_14.html', 'title': '14'},
               {'file': 'x17c1maccabees_15.html', 'title': '15'},
               {'file': 'x17c1maccabees_16.html', 'title': '16'}],
  'long': '1 Maccabees',
  'short': '1MA',
  'testament': 'Apocrypha',
  'tocfile': 'x17c1maccabees.html'},
 {'chapters': [{'file': 'IIMacc_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x17d2maccabees_1.html', 'title': '1'},
               {'file': 'x17d2maccabees_2.html', 'title': '2'},
               {'file': 'x17d2maccabees_3.html', 'title': '3'},
               {'file': 'x17d2maccabees_4.html', 'title': '4'},
               {'file': 'x17d2maccabees_5.html', 'title': '5'},
               {'file': 'x17d2maccabees_6.html', 'title': '6'},
               {'file': 'x17d2maccabees_7.html', 'title': '7'},
               {'file': 'x17d2maccabees_8.html', 'title': '8'},
               {'file': 'x17d2maccabees_9.html', 'title': '9'},
               {'file': 'x17d2maccabees_10.html', 'title': '10'},
               {'file': 'x17d2maccabees_11.html', 'title': '11'},
               {'file': 'x17d2maccabees_12.html', 'title': '12'},
               {'file': 'x17d2maccabees_13.html', 'title': '13'},
               {'file': 'x17d2maccabees_14.html', 'title': '14'},
               {'file': 'x17d2maccabees_15.html', 'title': '15'}],
  'long': '2 Maccabees',
  'short': '2MA',
  'testament': 'Apocrypha',
  'tocfile': 'x17d2maccabees.html'},
 {'chapters': [{'file': 'Job_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x18job_1.html', 'title': '1'},
               {'file': 'x18job_2.html', 'title': '2'},
               {'file': 'x18job_3.html', 'title': '3'},
               {'file': 'x18job_4.html', 'title': '4'},
               {'file': 'x18job_5.html', 'title': '5'},
               {'file': 'x18job_6.html', 'title': '6'},
               {'file': 'x18job_7.html', 'title': '7'},
               {'file': 'x18job_8.html', 'title': '8'},
               {'file': 'x18job_9.html', 'title': '9'},
               {'file': 'x18job_10.html', 'title': '10'},
               {'file': 'x18job_11.html', 'title': '11'},
               {'file': 'x18job_12.html', 'title': '12'},
               {'file': 'x18job_13.html', 'title': '13'},
               {'file': 'x18job_14.html', 'title': '14'},
               {'file': 'x18job_15.html', 'title': '15'},
               {'file': 'x18job_16.html', 'title': '16'},
               {'file': 'x18job_17.html', 'title': '17'},
               {'file': 'x18job_18.html', 'title': '18'},
               {'file': 'x18job_19.html', 'title': '19'},
               {'file': 'x18job_20.html', 'title': '20'},
               {'file': 'x18job_21.html', 'title': '21'},
               {'file': 'x18job_22.html', 'title': '22'},
               {'file': 'x18job_23.html', 'title': '23'},
               {'file': 'x18job_24.html', 'title': '24'},
               {'file': 'x18job_25.html', 'title': '25'},
               {'file': 'x18job_26.html', 'title': '26'},
               {'file': 'x18job_27.html', 'title': '27'},
               {'file': 'x18job_28.html', 'title': '28'},
               {'file': 'x18job_29.html', 'title': '29'},
               {'file': 'x18job_30.html', 'title': '30'},
               {'file': 'x18job_31.html', 'title': '31'},
               {'file': 'x18job_32.html', 'title': '32'},
               {'file': 'x18job_33.html', 'title': '33'},
               {'file': 'x18job_34.html', 'title': '34'},
               {'file': 'x18job_35.html', 'title': '35'},
               {'file': 'x18job_36.html', 'title': '36'},
               {'file': 'x18job_37.html', 'title': '37'},
               {'file': 'x18job_38.html', 'title': '38'},
               {'file': 'x18job_39.html', 'title': '39'},
               {'file': 'x18job_40.html', 'title': '40'},
               {'file': 'x18job_41.html', 'title': '41'},
               {'file': 'x18job_42.html', 'title': '42'}],
  'long': 'Job',
  'short': 'JOB',
  'testament': 'Old',
  'tocfile': 'x18job.html'},
 {'chapters': [{'file': 'Ps_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x19psalms_1.html', 'title': '1'},
               {'file': 'x19psalms_2.html', 'title': '2'},
               {'file': 'x19psalms_3.html', 'title': '3'},
               {'file': 'x19psalms_4.html', 'title': '4'},
               {'file': 'x19psalms_5.html', 'title': '5'},
               {'file': 'x19psalms_6.html', 'title': '6'},
               {'file': 'x19psalms_7.html', 'title': '7'},
               {'file': 'x19psalms_8.html', 'title': '8'},
               {'file': 'x19psalms_9.html', 'title': '9'},
               {'file': 'x19psalms_10.html', 'title': '10'},
               {'file': 'x19psalms_11.html', 'title': '11'},
               {'file': 'x19psalms_12.html', 'title': '12'},
               {'file': 'x19psalms_13.html', 'title': '13'},
               {'file': 'x19psalms_14.html', 'title': '14'},
               {'file': 'x19psalms_15.html', 'title': '15'},
               {'file': 'x19psalms_16.html', 'title': '16'},
               {'file': 'x19psalms_17.html', 'title': '17'},
               {'file': 'x19psalms_18.html', 'title': '18'},
               {'file': 'x19psalms_19.html', 'title': '19'},
               {'file': 'x19psalms_20.html', 'title': '20'},
               {'file': 'x19psalms_21.html', 'title': '21'},
               {'file': 'x19psalms_22.html', 'title': '22'},
               {'file': 'x19psalms_23.html', 'title': '23'},
               {'file': 'x19psalms_24.html', 'title': '24'},
               {'file': 'x19psalms_25.html', 'title': '25'},
               {'file': 'x19psalms_26.html', 'title': '26'},
               {'file': 'x19psalms_27.html', 'title': '27'},
               {'file': 'x19psalms_28.html', 'title': '28'},
               {'file': 'x19psalms_29.html', 'title': '29'},
               {'file': 'x19psalms_30.html', 'title': '30'},
               {'file': 'x19psalms_31.html', 'title': '31'},
               {'file': 'x19psalms_32.html', 'title': '32'},
               {'file': 'x19psalms_33.html', 'title': '33'},
               {'file': 'x19psalms_34.html', 'title': '34'},
               {'file': 'x19psalms_35.html', 'title': '35'},
               {'file': 'x19psalms_36.html', 'title': '36'},
               {'file': 'x19psalms_37.html', 'title': '37'},
               {'file': 'x19psalms_38.html', 'title': '38'},
               {'file': 'x19psalms_39.html', 'title': '39'},
               {'file': 'x19psalms_40.html', 'title': '40'},
               {'file': 'x19psalms_41.html', 'title': '41'},
               {'file': 'x19psalms_42.html', 'title': '42'},
               {'file': 'x19psalms_43.html', 'title': '43'},
               {'file': 'x19psalms_44.html', 'title': '44'},
               {'file': 'x19psalms_45.html', 'title': '45'},
               {'file': 'x19psalms_46.html', 'title': '46'},
               {'file': 'x19psalms_47.html', 'title': '47'},
               {'file': 'x19psalms_48.html', 'title': '48'},
               {'file': 'x19psalms_49.html', 'title': '49'},
               {'file': 'x19psalms_50.html', 'title': '50'},
               {'file': 'x19psalms_51.html', 'title': '51'},
               {'file': 'x19psalms_52.html', 'title': '52'},
               {'file': 'x19psalms_53.html', 'title': '53'},
               {'file': 'x19psalms_54.html', 'title': '54'},
               {'file': 'x19psalms_55.html', 'title': '55'},
               {'file': 'x19psalms_56.html', 'title': '56'},
               {'file': 'x19psalms_57.html', 'title': '57'},
               {'file': 'x19psalms_58.html', 'title': '58'},
               {'file': 'x19psalms_59.html', 'title': '59'},
               {'file': 'x19psalms_60.html', 'title': '60'},
               {'file': 'x19psalms_61.html', 'title': '61'},
               {'file': 'x19psalms_62.html', 'title': '62'},
               {'file': 'x19psalms_63.html', 'title': '63'},
               {'file': 'x19psalms_64.html', 'title': '64'},
               {'file': 'x19psalms_65.html', 'title': '65'},
               {'file': 'x19psalms_66.html', 'title': '66'},
               {'file': 'x19psalms_67.html', 'title': '67'},
               {'file': 'x19psalms_68.html', 'title': '68'},
               {'file': 'x19psalms_69.html', 'title': '69'},
               {'file': 'x19psalms_70.html', 'title': '70'},
               {'file': 'x19psalms_71.html', 'title': '71'},
               {'file': 'x19psalms_72.html', 'title': '72'},
               {'file': 'x19psalms_73.html', 'title': '73'},
               {'file': 'x19psalms_74.html', 'title': '74'},
               {'file': 'x19psalms_75.html', 'title': '75'},
               {'file': 'x19psalms_76.html', 'title': '76'},
               {'file': 'x19psalms_77.html', 'title': '77'},
               {'file': 'x19psalms_78.html', 'title': '78'},
               {'file': 'x19psalms_79.html', 'title': '79'},
               {'file': 'x19psalms_80.html', 'title': '80'},
               {'file': 'x19psalms_81.html', 'title': '81'},
               {'file': 'x19psalms_82.html', 'title': '82'},
               {'file': 'x19psalms_83.html', 'title': '83'},
               {'file': 'x19psalms_84.html', 'title': '84'},
               {'file': 'x19psalms_85.html', 'title': '85'},
               {'file': 'x19psalms_86.html', 'title': '86'},
               {'file': 'x19psalms_87.html', 'title': '87'},
               {'file': 'x19psalms_88.html', 'title': '88'},
               {'file': 'x19psalms_89.html', 'title': '89'},
               {'file': 'x19psalms_90.html', 'title': '90'},
               {'file': 'x19psalms_91.html', 'title': '91'},
               {'file': 'x19psalms_92.html', 'title': '92'},
               {'file': 'x19psalms_93.html', 'title': '93'},
               {'file': 'x19psalms_94.html', 'title': '94'},
               {'file': 'x19psalms_95.html', 'title': '95'},
               {'file': 'x19psalms_96.html', 'title': '96'},
               {'file': 'x19psalms_97.html', 'title': '97'},
               {'file': 'x19psalms_98.html', 'title': '98'},
               {'file': 'x19psalms_99.html', 'title': '99'},
               {'file': 'x19psalms_100.html', 'title': '100'},
               {'file': 'x19psalms_101.html', 'title': '101'},
               {'file': 'x19psalms_102.html', 'title': '102'},
               {'file': 'x19psalms_103.html', 'title': '103'},
               {'file': 'x19psalms_104.html', 'title': '104'},
               {'file': 'x19psalms_105.html', 'title': '105'},
               {'file': 'x19psalms_106.html', 'title': '106'},
               {'file': 'x19psalms_107.html', 'title': '107'},
               {'file': 'x19psalms_108.html', 'title': '108'},
               {'file': 'x19psalms_109.html', 'title': '109'},
               {'file': 'x19psalms_110.html', 'title': '110'},
               {'file': 'x19psalms_111.html', 'title': '111'},
               {'file': 'x19psalms_112.html', 'title': '112'},
               {'file': 'x19psalms_113.html', 'title': '113'},
               {'file': 'x19psalms_114.html', 'title': '114'},
               {'file': 'x19psalms_115.html', 'title': '115'},
               {'file': 'x19psalms_116.html', 'title': '116'},
               {'file': 'x19psalms_117.html', 'title': '117'},
               {'file': 'x19psalms_118.html', 'title': '118'},
               {'file': 'x19psalms_119.html', 'title': '119'},
               {'file': 'x19psalms_120.html', 'title': '120'},
               {'file': 'x19psalms_121.html', 'title': '121'},
               {'file': 'x19psalms_122.html', 'title': '122'},
               {'file': 'x19psalms_123.html', 'title': '123'},
               {'file': 'x19psalms_124.html', 'title': '124'},
               {'file': 'x19psalms_125.html', 'title': '125'},
               {'file': 'x19psalms_126.html', 'title': '126'},
               {'file': 'x19psalms_127.html', 'title': '127'},
               {'file': 'x19psalms_128.html', 'title': '128'},
               {'file': 'x19psalms_129.html', 'title': '129'},
               {'file': 'x19psalms_130.html', 'title': '130'},
               {'file': 'x19psalms_131.html', 'title': '131'},
               {'file': 'x19psalms_132.html', 'title': '132'},
               {'file': 'x19psalms_133.html', 'title': '133'},
               {'file': 'x19psalms_134.html', 'title': '134'},
               {'file': 'x19psalms_135.html', 'title': '135'},
               {'file': 'x19psalms_136.html', 'title': '136'},
               {'file': 'x19psalms_137.html', 'title': '137'},
               {'file': 'x19psalms_138.html', 'title': '138'},
               {'file': 'x19psalms_139.html', 'title': '139'},
               {'file': 'x19psalms_140.html', 'title': '140'},
               {'file': 'x19psalms_141.html', 'title': '141'},
               {'file': 'x19psalms_142.html', 'title': '142'},
               {'file': 'x19psalms_143.html', 'title': '143'},
               {'file': 'x19psalms_144.html', 'title': '144'},
               {'file': 'x19psalms_145.html', 'title': '145'},
               {'file': 'x19psalms_146.html', 'title': '146'},
               {'file': 'x19psalms_147.html', 'title': '147'},
               {'file': 'x19psalms_148.html', 'title': '148'},
               {'file': 'x19psalms_149.html', 'title': '149'},
               {'file': 'x19psalms_150.html', 'title': '150'}],
  'long': 'Psalms',
  'short': 'PSA',
  'testament': 'Old',
  'tocfile': 'x19psalms.html'},
 {'chapters': [{'file': 'Pr_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x20proverbs_1.html', 'title': '1'},
               {'file': 'x20proverbs_2.html', 'title': '2'},
               {'file': 'x20proverbs_3.html', 'title': '3'},
               {'file': 'x20proverbs_4.html', 'title': '4'},
               {'file': 'x20proverbs_5.html', 'title': '5'},
               {'file': 'x20proverbs_6.html', 'title': '6'},
               {'file': 'x20proverbs_7.html', 'title': '7'},
               {'file': 'x20proverbs_8.html', 'title': '8'},
               {'file': 'x20proverbs_9.html', 'title': '9'},
               {'file': 'x20proverbs_10.html', 'title': '10'},
               {'file': 'x20proverbs_11.html', 'title': '11'},
               {'file': 'x20proverbs_12.html', 'title': '12'},
               {'file': 'x20proverbs_13.html', 'title': '13'},
               {'file': 'x20proverbs_14.html', 'title': '14'},
               {'file': 'x20proverbs_15.html', 'title': '15'},
               {'file': 'x20proverbs_16.html', 'title': '16'},
               {'file': 'x20proverbs_17.html', 'title': '17'},
               {'file': 'x20proverbs_18.html', 'title': '18'},
               {'file': 'x20proverbs_19.html', 'title': '19'},
               {'file': 'x20proverbs_20.html', 'title': '20'},
               {'file': 'x20proverbs_21.html', 'title': '21'},
               {'file': 'x20proverbs_22.html', 'title': '22'},
               {'file': 'x20proverbs_23.html', 'title': '23'},
               {'file': 'x20proverbs_24.html', 'title': '24'},
               {'file': 'x20proverbs_25.html', 'title': '25'},
               {'file': 'x20proverbs_26.html', 'title': '26'},
               {'file': 'x20proverbs_27.html', 'title': '27'},
               {'file': 'x20proverbs_28.html', 'title': '28'},
               {'file': 'x20proverbs_29.html', 'title': '29'},
               {'file': 'x20proverbs_30.html', 'title': '30'},
               {'file': 'x20proverbs_31.html', 'title': '31'}],
  'long': 'Proverbs',
  'short': 'PRO',
  'testament': 'Old',
  'tocfile': 'x20proverbs.html'},
 {'chapters': [{'file': 'Eccl_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x21ecclesiastes_1.html', 'title': '1'},
               {'file': 'x21ecclesiastes_2.html', 'title': '2'},
               {'file': 'x21ecclesiastes_3.html', 'title': '3'},
               {'file': 'x21ecclesiastes_4.html', 'title': '4'},
               {'file': 'x21ecclesiastes_5.html', 'title': '5'},
               {'file': 'x21ecclesiastes_6.html', 'title': '6'},
               {'file': 'x21ecclesiastes_7.html', 'title': '7'},
               {'file': 'x21ecclesiastes_8.html', 'title': '8'},
               {'file': 'x21ecclesiastes_9.html', 'title': '9'},
               {'file': 'x21ecclesiastes_10.html', 'title': '10'},
               {'file': 'x21ecclesiastes_11.html', 'title': '11'},
               {'file': 'x21ecclesiastes_12.html', 'title': '12'}],
  'long': 'Ecclesiastes',
  'short': 'ECC',
  'testament': 'Old',
  'tocfile': 'x21ecclesiastes.html'},
 {'chapters': [{'file': 'Song_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x22songofsongs_1.html', 'title': '1'},
               {'file': 'x22songofsongs_2.html', 'title': '2'},
               {'file': 'x22songofsongs_3.html', 'title': '3'},
               {'file': 'x22songofsongs_4.html', 'title': '4'},
               {'file': 'x22songofsongs_5.html', 'title': '5'},
               {'file': 'x22songofsongs_6.html', 'title': '6'},
               {'file': 'x22songofsongs_7.html', 'title': '7'},
               {'file': 'x22songofsongs_8.html', 'title': '8'}],
  'long': 'Song of Solomon',
  'short': 'SNG',
  'testament': 'Old',
  'tocfile': 'x22songofsongs.html'},
 {'chapters': [{'file': 'Wis_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x22bwisdom_1.html', 'title': '1'},
               {'file': 'x22bwisdom_2.html', 'title': '2'},
               {'file': 'x22bwisdom_3.html', 'title': '3'},
               {'file': 'x22bwisdom_4.html', 'title': '4'},
               {'file': 'x22bwisdom_5.html', 'title': '5'},
               {'file': 'x22bwisdom_6.html', 'title': '6'},
               {'file': 'x22bwisdom_7.html', 'title': '7'},
               {'file': 'x22bwisdom_8.html', 'title': '8'},
               {'file': 'x22bwisdom_9.html', 'title': '9'},
               {'file': 'x22bwisdom_10.html', 'title': '10'},
               {'file': 'x22bwisdom_11.html', 'title': '11'},
               {'file': 'x22bwisdom_12.html', 'title': '12'},
               {'file': 'x22bwisdom_13.html', 'title': '13'},
               {'file': 'x22bwisdom_14.html', 'title': '14'},
               {'file': 'x22bwisdom_15.html', 'title': '15'},
               {'file': 'x22bwisdom_16.html', 'title': '16'},
               {'file': 'x22bwisdom_17.html', 'title': '17'},
               {'file': 'x22bwisdom_18.html', 'title': '18'},
               {'file': 'x22bwisdom_19.html', 'title': '19'}],
  'long': 'Wisdom',
  'short': 'WIS',
  'testament': 'Apocrypha',
  'tocfile': 'x22bwisdom.html'},
 {'chapters': [{'file': 'Sir_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x22csirachecclesiasticus_1.html', 'title': '1'},
               {'file': 'x22csirachecclesiasticus_2.html', 'title': '2'},
               {'file': 'x22csirachecclesiasticus_3.html', 'title': '3'},
               {'file': 'x22csirachecclesiasticus_4.html', 'title': '4'},
               {'file': 'x22csirachecclesiasticus_5.html', 'title': '5'},
               {'file': 'x22csirachecclesiasticus_6.html', 'title': '6'},
               {'file': 'x22csirachecclesiasticus_7.html', 'title': '7'},
               {'file': 'x22csirachecclesiasticus_8.html', 'title': '8'},
               {'file': 'x22csirachecclesiasticus_9.html', 'title': '9'},
               {'file': 'x22csirachecclesiasticus_10.html', 'title': '10'},
               {'file': 'x22csirachecclesiasticus_11.html', 'title': '11'},
               {'file': 'x22csirachecclesiasticus_12.html', 'title': '12'},
               {'file': 'x22csirachecclesiasticus_13.html', 'title': '13'},
               {'file': 'x22csirachecclesiasticus_14.html', 'title': '14'},
               {'file': 'x22csirachecclesiasticus_15.html', 'title': '15'},
               {'file': 'x22csirachecclesiasticus_16.html', 'title': '16'},
               {'file': 'x22csirachecclesiasticus_17.html', 'title': '17'},
               {'file': 'x22csirachecclesiasticus_18.html', 'title': '18'},
               {'file': 'x22csirachecclesiasticus_19.html', 'title': '19'},
               {'file': 'x22csirachecclesiasticus_20.html', 'title': '20'},
               {'file': 'x22csirachecclesiasticus_21.html', 'title': '21'},
               {'file': 'x22csirachecclesiasticus_22.html', 'title': '22'},
               {'file': 'x22csirachecclesiasticus_23.html', 'title': '23'},
               {'file': 'x22csirachecclesiasticus_24.html', 'title': '24'},
               {'file': 'x22csirachecclesiasticus_25.html', 'title': '25'},
               {'file': 'x22csirachecclesiasticus_26.html', 'title': '26'},
               {'file': 'x22csirachecclesiasticus_27.html', 'title': '27'},
               {'file': 'x22csirachecclesiasticus_28.html', 'title': '28'},
               {'file': 'x22csirachecclesiasticus_29.html', 'title': '29'},
               {'file': 'x22csirachecclesiasticus_30.html', 'title': '30'},
               {'file': 'x22csirachecclesiasticus_31.html', 'title': '31'},
               {'file': 'x22csirachecclesiasticus_32.html', 'title': '32'},
               {'file': 'x22csirachecclesiasticus_33.html', 'title': '33'},
               {'file': 'x22csirachecclesiasticus_34.html', 'title': '34'},
               {'file': 'x22csirachecclesiasticus_35.html', 'title': '35'},
               {'file': 'x22csirachecclesiasticus_36.html', 'title': '36'},
               {'file': 'x22csirachecclesiasticus_37.html', 'title': '37'},
               {'file': 'x22csirachecclesiasticus_38.html', 'title': '38'},
               {'file': 'x22csirachecclesiasticus_39.html', 'title': '39'},
               {'file': 'x22csirachecclesiasticus_40.html', 'title': '40'},
               {'file': 'x22csirachecclesiasticus_41.html', 'title': '41'},
               {'file': 'x22csirachecclesiasticus_42.html', 'title': '42'},
               {'file': 'x22csirachecclesiasticus_43.html', 'title': '43'},
               {'file': 'x22csirachecclesiasticus_44.html', 'title': '44'},
               {'file': 'x22csirachecclesiasticus_45.html', 'title': '45'},
               {'file': 'x22csirachecclesiasticus_46.html', 'title': '46'},
               {'file': 'x22csirachecclesiasticus_47.html', 'title': '47'},
               {'file': 'x22csirachecclesiasticus_48.html', 'title': '48'},
               {'file': 'x22csirachecclesiasticus_49.html', 'title': '49'},
               {'file': 'x22csirachecclesiasticus_50.html', 'title': '50'},
               {'file': 'x22csirachecclesiasticus_51.html', 'title': '51'}],
  'long': 'Sirach',
  'short': 'SIR',
  'testament': 'Apocrypha',
  'tocfile': 'x22csirachecclesiasticus.html'},
 {'chapters': [{'file': 'Isa_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x23isaiah_1.html', 'title': '1'},
               {'file': 'x23isaiah_2.html', 'title': '2'},
               {'file': 'x23isaiah_3.html', 'title': '3'},
               {'file': 'x23isaiah_4.html', 'title': '4'},
               {'file': 'x23isaiah_5.html', 'title': '5'},
               {'file': 'x23isaiah_6.html', 'title': '6'},
               {'file': 'x23isaiah_7.html', 'title': '7'},
               {'file': 'x23isaiah_8.html', 'title': '8'},
               {'file': 'x23isaiah_9.html', 'title': '9'},
               {'file': 'x23isaiah_10.html', 'title': '10'},
               {'file': 'x23isaiah_11.html', 'title': '11'},
               {'file': 'x23isaiah_12.html', 'title': '12'},
               {'file': 'x23isaiah_13.html', 'title': '13'},
               {'file': 'x23isaiah_14.html', 'title': '14'},
               {'file': 'x23isaiah_15.html', 'title': '15'},
               {'file': 'x23isaiah_16.html', 'title': '16'},
               {'file': 'x23isaiah_17.html', 'title': '17'},
               {'file': 'x23isaiah_18.html', 'title': '18'},
               {'file': 'x23isaiah_19.html', 'title': '19'},
               {'file': 'x23isaiah_20.html', 'title': '20'},
               {'file': 'x23isaiah_21.html', 'title': '21'},
               {'file': 'x23isaiah_22.html', 'title': '22'},
               {'file': 'x23isaiah_23.html', 'title': '23'},
               {'file': 'x23isaiah_24.html', 'title': '24'},
               {'file': 'x23isaiah_25.html', 'title': '25'},
               {'file': 'x23isaiah_26.html', 'title': '26'},
               {'file': 'x23isaiah_27.html', 'title': '27'},
               {'file': 'x23isaiah_28.html', 'title': '28'},
               {'file': 'x23isaiah_29.html', 'title': '29'},
               {'file': 'x23isaiah_30.html', 'title': '30'},
               {'file': 'x23isaiah_31.html', 'title': '31'},
               {'file': 'x23isaiah_32.html', 'title': '32'},
               {'file': 'x23isaiah_33.html', 'title': '33'},
               {'file': 'x23isaiah_34.html', 'title': '34'},
               {'file': 'x23isaiah_35.html', 'title': '35'},
               {'file': 'x23isaiah_36.html', 'title': '36'},
               {'file': 'x23isaiah_37.html', 'title': '37'},
               {'file': 'x23isaiah_38.html', 'title': '38'},
               {'file': 'x23isaiah_39.html', 'title': '39'},
               {'file': 'x23isaiah_40.html', 'title': '40'},
               {'file': 'x23isaiah_41.html', 'title': '41'},
               {'file': 'x23isaiah_42.html', 'title': '42'},
               {'file': 'x23isaiah_43.html', 'title': '43'},
               {'file': 'x23isaiah_44.html', 'title': '44'},
               {'file': 'x23isaiah_45.html', 'title': '45'},
               {'file': 'x23isaiah_46.html', 'title': '46'},
               {'file': 'x23isaiah_47.html', 'title': '47'},
               {'file': 'x23isaiah_48.html', 'title': '48'},
               {'file': 'x23isaiah_49.html', 'title': '49'},
               {'file': 'x23isaiah_50.html', 'title': '50'},
               {'file': 'x23isaiah_51.html', 'title': '51'},
               {'file': 'x23isaiah_52.html', 'title': '52'},
               {'file': 'x23isaiah_53.html', 'title': '53'},
               {'file': 'x23isaiah_54.html', 'title': '54'},
               {'file': 'x23isaiah_55.html', 'title': '55'},
               {'file': 'x23isaiah_56.html', 'title': '56'},
               {'file': 'x23isaiah_57.html', 'title': '57'},
               {'file': 'x23isaiah_58.html', 'title': '58'},
               {'file': 'x23isaiah_59.html', 'title': '59'},
               {'file': 'x23isaiah_60.html', 'title': '60'},
               {'file': 'x23isaiah_61.html', 'title': '61'},
               {'file': 'x23isaiah_62.html', 'title': '62'},
               {'file': 'x23isaiah_63.html', 'title': '63'},
               {'file': 'x23isaiah_64.html', 'title': '64'},
               {'file': 'x23isaiah_65.html', 'title': '65'},
               {'file': 'x23isaiah_66.html', 'title': '66'}],
  'long': 'Isaiah',
  'short': 'ISA',
  'testament': 'Old',
  'tocfile': 'x23isaiah.html'},
 {'chapters': [{'file': 'Jer_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x24jeremiah_1.html', 'title': '1'},
               {'file': 'x24jeremiah_2.html', 'title': '2'},
               {'file': 'x24jeremiah_3.html', 'title': '3'},
               {'file': 'x24jeremiah_4.html', 'title': '4'},
               {'file': 'x24jeremiah_5.html', 'title': '5'},
               {'file': 'x24jeremiah_6.html', 'title': '6'},
               {'file': 'x24jeremiah_7.html', 'title': '7'},
               {'file': 'x24jeremiah_8.html', 'title': '8'},
               {'file': 'x24jeremiah_9.html', 'title': '9'},
               {'file': 'x24jeremiah_10.html', 'title': '10'},
               {'file': 'x24jeremiah_11.html', 'title': '11'},
               {'file': 'x24jeremiah_12.html', 'title': '12'},
               {'file': 'x24jeremiah_13.html', 'title': '13'},
               {'file': 'x24jeremiah_14.html', 'title': '14'},
               {'file': 'x24jeremiah_15.html', 'title': '15'},
               {'file': 'x24jeremiah_16.html', 'title': '16'},
               {'file': 'x24jeremiah_17.html', 'title': '17'},
               {'file': 'x24jeremiah_18.html', 'title': '18'},
               {'file': 'x24jeremiah_19.html', 'title': '19'},
               {'file': 'x24jeremiah_20.html', 'title': '20'},
               {'file': 'x24jeremiah_21.html', 'title': '21'},
               {'file': 'x24jeremiah_22.html', 'title': '22'},
               {'file': 'x24jeremiah_23.html', 'title': '23'},
               {'file': 'x24jeremiah_24.html', 'title': '24'},
               {'file': 'x24jeremiah_25.html', 'title': '25'},
               {'file': 'x24jeremiah_26.html', 'title': '26'},
               {'file': 'x24jeremiah_27.html', 'title': '27'},
               {'file': 'x24jeremiah_28.html', 'title': '28'},
               {'file': 'x24jeremiah_29.html', 'title': '29'},
               {'file': 'x24jeremiah_30.html', 'title': '30'},
               {'file': 'x24jeremiah_31.html', 'title': '31'},
               {'file': 'x24jeremiah_32.html', 'title': '32'},
               {'file': 'x24jeremiah_33.html', 'title': '33'},
               {'file': 'x24jeremiah_34.html', 'title': '34'},
               {'file': 'x24jeremiah_35.html', 'title': '35'},
               {'file': 'x24jeremiah_36.html', 'title': '36'},
               {'file': 'x24jeremiah_37.html', 'title': '37'},
               {'file': 'x24jeremiah_38.html', 'title': '38'},
               {'file': 'x24jeremiah_39.html', 'title': '39'},
               {'file': 'x24jeremiah_40.html', 'title': '40'},
               {'file': 'x24jeremiah_41.html', 'title': '41'},
               {'file': 'x24jeremiah_42.html', 'title': '42'},
               {'file': 'x24jeremiah_43.html', 'title': '43'},
               {'file': 'x24jeremiah_44.html', 'title': '44'},
               {'file': 'x24jeremiah_45.html', 'title': '45'},
               {'file': 'x24jeremiah_46.html', 'title': '46'},
               {'file': 'x24jeremiah_47.html', 'title': '47'},
               {'file': 'x24jeremiah_48.html', 'title': '48'},
               {'file': 'x24jeremiah_49.html', 'title': '49'},
               {'file': 'x24jeremiah_50.html', 'title': '50'},
               {'file': 'x24jeremiah_51.html', 'title': '51'},
               {'file': 'x24jeremiah_52.html', 'title': '52'}],
  'long': 'Jeremiah',
  'short': 'JER',
  'testament': 'Old',
  'tocfile': 'x24jeremiah.html'},
 {'chapters': [{'file': 'Lam_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x25lamentations_1.html', 'title': '1'},
               {'file': 'x25lamentations_2.html', 'title': '2'},
               {'file': 'x25lamentations_3.html', 'title': '3'},
               {'file': 'x25lamentations_4.html', 'title': '4'},
               {'file': 'x25lamentations_5.html', 'title': '5'}],
  'long': 'Lamentations',
  'short': 'LAM',
  'testament': 'Old',
  'tocfile': 'x25lamentations.html'},
 {'chapters': [{'file': 'Bar_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x25bbaruch_1.html', 'title': '1'},
               {'file': 'x25bbaruch_2.html', 'title': '2'},
               {'file': 'x25bbaruch_3.html', 'title': '3'},
               {'file': 'x25bbaruch_4.html', 'title': '4'},
               {'file': 'x25bbaruch_5.html', 'title': '5'},
               {'file': 'x25bbaruch_6.html', 'title': '6'}],
  'long': 'Baruch',
  'short': 'BAR',
  'testament': 'Apocrypha',
  'tocfile': 'x25bbaruch.html'},
 {'chapters': [{'file': 'Ezek_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x26ezekiel_1.html', 'title': '1'},
               {'file': 'x26ezekiel_2.html', 'title': '2'},
               {'file': 'x26ezekiel_3.html', 'title': '3'},
               {'file': 'x26ezekiel_4.html', 'title': '4'},
               {'file': 'x26ezekiel_5.html', 'title': '5'},
               {'file': 'x26ezekiel_6.html', 'title': '6'},
               {'file': 'x26ezekiel_7.html', 'title': '7'},
               {'file': 'x26ezekiel_8.html', 'title': '8'},
               {'file': 'x26ezekiel_9.html', 'title': '9'},
               {'file': 'x26ezekiel_10.html', 'title': '10'},
               {'file': 'x26ezekiel_11.html', 'title': '11'},
               {'file': 'x26ezekiel_12.html', 'title': '12'},
               {'file': 'x26ezekiel_13.html', 'title': '13'},
               {'file': 'x26ezekiel_14.html', 'title': '14'},
               {'file': 'x26ezekiel_15.html', 'title': '15'},
               {'file': 'x26ezekiel_16.html', 'title': '16'},
               {'file': 'x26ezekiel_17.html', 'title': '17'},
               {'file': 'x26ezekiel_18.html', 'title': '18'},
               {'file': 'x26ezekiel_19.html', 'title': '19'},
               {'file': 'x26ezekiel_20.html', 'title': '20'},
               {'file': 'x26ezekiel_21.html', 'title': '21'},
               {'file': 'x26ezekiel_22.html', 'title': '22'},
               {'file': 'x26ezekiel_23.html', 'title': '23'},
               {'file': 'x26ezekiel_24.html', 'title': '24'},
               {'file': 'x26ezekiel_25.html', 'title': '25'},
               {'file': 'x26ezekiel_26.html', 'title': '26'},
               {'file': 'x26ezekiel_27.html', 'title': '27'},
               {'file': 'x26ezekiel_28.html', 'title': '28'},
               {'file': 'x26ezekiel_29.html', 'title': '29'},
               {'file': 'x26ezekiel_30.html', 'title': '30'},
               {'file': 'x26ezekiel_31.html', 'title': '31'},
               {'file': 'x26ezekiel_32.html', 'title': '32'},
               {'file': 'x26ezekiel_33.html', 'title': '33'},
               {'file': 'x26ezekiel_34.html', 'title': '34'},
               {'file': 'x26ezekiel_35.html', 'title': '35'},
               {'file': 'x26ezekiel_36.html', 'title': '36'},
               {'file': 'x26ezekiel_37.html', 'title': '37'},
               {'file': 'x26ezekiel_38.html', 'title': '38'},
               {'file': 'x26ezekiel_39.html', 'title': '39'},
               {'file': 'x26ezekiel_40.html', 'title': '40'},
               {'file': 'x26ezekiel_41.html', 'title': '41'},
               {'file': 'x26ezekiel_42.html', 'title': '42'},
               {'file': 'x26ezekiel_43.html', 'title': '43'},
               {'file': 'x26ezekiel_44.html', 'title': '44'},
               {'file': 'x26ezekiel_45.html', 'title': '45'},
               {'file': 'x26ezekiel_46.html', 'title': '46'},
               {'file': 'x26ezekiel_47.html', 'title': '47'},
               {'file': 'x26ezekiel_48.html', 'title': '48'}],
  'long': 'Ezekiel',
  'short': 'EZK',
  'testament': 'Old',
  'tocfile': 'x26ezekiel.html'},
 {'chapters': [{'file': 'Dan_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x27bdaniel_1.html', 'title': '1'},
               {'file': 'x27bdaniel_2.html', 'title': '2'},
               {'file': 'x27bdaniel_3.html', 'title': '3'},
               {'file': 'x27bdaniel_4.html', 'title': '4'},
               {'file': 'x27bdaniel_5.html', 'title': '5'},
               {'file': 'x27bdaniel_6.html', 'title': '6'},
               {'file': 'x27bdaniel_7.html', 'title': '7'},
               {'file': 'x27bdaniel_8.html', 'title': '8'},
               {'file': 'x27bdaniel_9.html', 'title': '9'},
               {'file': 'x27bdaniel_10.html', 'title': '10'},
               {'file': 'x27bdaniel_11.html', 'title': '11'},
               {'file': 'x27bdaniel_12.html', 'title': '12'},
               {'file': 'x27bdaniel_13.html', 'title': '13'},
               {'file': 'x27bdaniel_14.html', 'title': '14'}],
  'long': 'Daniel',
  'short': 'DAN',
  'testament': 'Old',
  'tocfile': 'x27bdaniel.html'},
 {'chapters': [{'file': 'Hos_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x28hosea_1.html', 'title': '1'},
               {'file': 'x28hosea_2.html', 'title': '2'},
               {'file': 'x28hosea_3.html', 'title': '3'},
               {'file': 'x28hosea_4.html', 'title': '4'},
               {'file': 'x28hosea_5.html', 'title': '5'},
               {'file': 'x28hosea_6.html', 'title': '6'},
               {'file': 'x28hosea_7.html', 'title': '7'},
               {'file': 'x28hosea_8.html', 'title': '8'},
               {'file': 'x28hosea_9.html', 'title': '9'},
               {'file': 'x28hosea_10.html', 'title': '10'},
               {'file': 'x28hosea_11.html', 'title': '11'},
               {'file': 'x28hosea_12.html', 'title': '12'},
               {'file': 'x28hosea_13.html', 'title': '13'},
               {'file': 'x28hosea_14.html', 'title': '14'}],
  'long': 'Hosea',
  'short': 'HOS',
  'testament': 'Old',
  'tocfile': 'x28hosea.html'},
 {'chapters': [{'file': 'Joel_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x29joel_1.html', 'title': '1'},
               {'file': 'x29joel_2.html', 'title': '2'},
               {'file': 'x29joel_3.html', 'title': '3'}],
  'long': 'Joel',
  'short': 'JOL',
  'testament': 'Old',
  'tocfile': 'x29joel.html'},
 {'chapters': [{'file': 'Amos_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x30amos_1.html', 'title': '1'},
               {'file': 'x30amos_2.html', 'title': '2'},
               {'file': 'x30amos_3.html', 'title': '3'},
               {'file': 'x30amos_4.html', 'title': '4'},
               {'file': 'x30amos_5.html', 'title': '5'},
               {'file': 'x30amos_6.html', 'title': '6'},
               {'file': 'x30amos_7.html', 'title': '7'},
               {'file': 'x30amos_8.html', 'title': '8'},
               {'file': 'x30amos_9.html', 'title': '9'}],
  'long': 'Amos',
  'short': 'AMO',
  'testament': 'Old',
  'tocfile': 'x30amos.html'},
 {'chapters': [{'file': 'Obad_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x31obadiah_1.html', 'title': '1'}],
  'long': 'Obadiah',
  'short': 'OBA',
  'testament': 'Old',
  'tocfile': 'x31obadiah.html'},
 {'chapters': [{'file': 'Jon_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x32jonah_1.html', 'title': '1'},
               {'file': 'x32jonah_2.html', 'title': '2'},
               {'file': 'x32jonah_3.html', 'title': '3'},
               {'file': 'x32jonah_4.html', 'title': '4'}],
  'long': 'Jonah',
  'short': 'JON',
  'testament': 'Old',
  'tocfile': 'x32jonah.html'},
 {'chapters': [{'file': 'Mic_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x33micah_1.html', 'title': '1'},
               {'file': 'x33micah_2.html', 'title': '2'},
               {'file': 'x33micah_3.html', 'title': '3'},
               {'file': 'x33micah_4.html', 'title': '4'},
               {'file': 'x33micah_5.html', 'title': '5'},
               {'file': 'x33micah_6.html', 'title': '6'},
               {'file': 'x33micah_7.html', 'title': '7'}],
  'long': 'Micah',
  'short': 'MIC',
  'testament': 'Old',
  'tocfile': 'x33micah.html'},
 {'chapters': [{'file': 'Nah_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x34nahum_1.html', 'title': '1'},
               {'file': 'x34nahum_2.html', 'title': '2'},
               {'file': 'x34nahum_3.html', 'title': '3'}],
  'long': 'Nahum',
  'short': 'NAM',
  'testament': 'Old',
  'tocfile': 'x34nahum.html'},
 {'chapters': [{'file': 'Hab_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x35habakkuk_1.html', 'title': '1'},
               {'file': 'x35habakkuk_2.html', 'title': '2'},
               {'file': 'x35habakkuk_3.html', 'title': '3'}],
  'long': 'Habakkuk',
  'short': 'HAB',
  'testament': 'Old',
  'tocfile': 'x35habakkuk.html'},
 {'chapters': [{'file': 'Zeph_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x36zephaniah_1.html', 'title': '1'},
               {'file': 'x36zephaniah_2.html', 'title': '2'},
               {'file': 'x36zephaniah_3.html', 'title': '3'}],
  'long': 'Zephaniah',
  'short': 'ZEP',
  'testament': 'Old',
  'tocfile': 'x36zephaniah.html'},
 {'chapters': [{'file': 'Hagg_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x37haggai_1.html', 'title': '1'},
               {'file': 'x37haggai_2.html', 'title': '2'}],
  'long': 'Haggai',
  'short': 'HAG',
  'testament': 'Old',
  'tocfile': 'x37haggai.html'},
 {'chapters': [{'file': 'Zech_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x38zechariah_1.html', 'title': '1'},
               {'file': 'x38zechariah_2.html', 'title': '2'},
               {'file': 'x38zechariah_3.html', 'title': '3'},
               {'file': 'x38zechariah_4.html', 'title': '4'},
               {'file': 'x38zechariah_5.html', 'title': '5'},
               {'file': 'x38zechariah_6.html', 'title': '6'},
               {'file': 'x38zechariah_7.html', 'title': '7'},
               {'file': 'x38zechariah_8.html', 'title': '8'},
               {'file': 'x38zechariah_9.html', 'title': '9'},
               {'file': 'x38zechariah_10.html', 'title': '10'},
               {'file': 'x38zechariah_11.html', 'title': '11'},
               {'file': 'x38zechariah_12.html', 'title': '12'},
               {'file': 'x38zechariah_13.html', 'title': '13'},
               {'file': 'x38zechariah_14.html', 'title': '14'}],
  'long': 'Zechariah',
  'short': 'ZEC',
  'testament': 'Old',
  'tocfile': 'x38zechariah.html'},
 {'chapters': [{'file': 'Mal_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x39malachi_1.html', 'title': '1'},
               {'file': 'x39malachi_2.html', 'title': '2'},
               {'file': 'x39malachi_3.html', 'title': '3'},
               {'file': 'x39malachi_4.html', 'title': '4'}],
  'long': 'Malachi',
  'short': 'MAL',
  'testament': 'Old',
  'tocfile': 'x39malachi.html'},
 {'chapters': [{'file': 'Matt_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x40matthew_1.html', 'title': '1'},
               {'file': 'x40matthew_2.html', 'title': '2'},
               {'file': 'x40matthew_3.html', 'title': '3'},
               {'file': 'x40matthew_4.html', 'title': '4'},
               {'file': 'x40matthew_5.html', 'title': '5'},
               {'file': 'x40matthew_6.html', 'title': '6'},
               {'file': 'x40matthew_7.html', 'title': '7'},
               {'file': 'x40matthew_8.html', 'title': '8'},
               {'file': 'x40matthew_9.html', 'title': '9'},
               {'file': 'x40matthew_10.html', 'title': '10'},
               {'file': 'x40matthew_11.html', 'title': '11'},
               {'file': 'x40matthew_12.html', 'title': '12'},
               {'file': 'x40matthew_13.html', 'title': '13'},
               {'file': 'x40matthew_14.html', 'title': '14'},
               {'file': 'x40matthew_15.html', 'title': '15'},
               {'file': 'x40matthew_16.html', 'title': '16'},
               {'file': 'x40matthew_17.html', 'title': '17'},
               {'file': 'x40matthew_18.html', 'title': '18'},
               {'file': 'x40matthew_19.html', 'title': '19'},
               {'file': 'x40matthew_20.html', 'title': '20'},
               {'file': 'x40matthew_21.html', 'title': '21'},
               {'file': 'x40matthew_22.html', 'title': '22'},
               {'file': 'x40matthew_23.html', 'title': '23'},
               {'file': 'x40matthew_24.html', 'title': '24'},
               {'file': 'x40matthew_25.html', 'title': '25'},
               {'file': 'x40matthew_26.html', 'title': '26'},
               {'file': 'x40matthew_27.html', 'title': '27'},
               {'file': 'x40matthew_28.html', 'title': '28'}],
  'long': 'Matthew',
  'short': 'MAT',
  'testament': 'New',
  'tocfile': 'x40matthew.html'},
 {'chapters': [{'file': 'Mark_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x41mark_1.html', 'title': '1'},
               {'file': 'x41mark_2.html', 'title': '2'},
               {'file': 'x41mark_3.html', 'title': '3'},
               {'file': 'x41mark_4.html', 'title': '4'},
               {'file': 'x41mark_5.html', 'title': '5'},
               {'file': 'x41mark_6.html', 'title': '6'},
               {'file': 'x41mark_7.html', 'title': '7'},
               {'file': 'x41mark_8.html', 'title': '8'},
               {'file': 'x41mark_9.html', 'title': '9'},
               {'file': 'x41mark_10.html', 'title': '10'},
               {'file': 'x41mark_11.html', 'title': '11'},
               {'file': 'x41mark_12.html', 'title': '12'},
               {'file': 'x41mark_13.html', 'title': '13'},
               {'file': 'x41mark_14.html', 'title': '14'},
               {'file': 'x41mark_15.html', 'title': '15'},
               {'file': 'x41mark_16.html', 'title': '16'}],
  'long': 'Mark',
  'short': 'MRK',
  'testament': 'New',
  'tocfile': 'x41mark.html'},
 {'chapters': [{'file': 'Luke_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x42luke_1.html', 'title': '1'},
               {'file': 'x42luke_2.html', 'title': '2'},
               {'file': 'x42luke_3.html', 'title': '3'},
               {'file': 'x42luke_4.html', 'title': '4'},
               {'file': 'x42luke_5.html', 'title': '5'},
               {'file': 'x42luke_6.html', 'title': '6'},
               {'file': 'x42luke_7.html', 'title': '7'},
               {'file': 'x42luke_8.html', 'title': '8'},
               {'file': 'x42luke_9.html', 'title': '9'},
               {'file': 'x42luke_10.html', 'title': '10'},
               {'file': 'x42luke_11.html', 'title': '11'},
               {'file': 'x42luke_12.html', 'title': '12'},
               {'file': 'x42luke_13.html', 'title': '13'},
               {'file': 'x42luke_14.html', 'title': '14'},
               {'file': 'x42luke_15.html', 'title': '15'},
               {'file': 'x42luke_16.html', 'title': '16'},
               {'file': 'x42luke_17.html', 'title': '17'},
               {'file': 'x42luke_18.html', 'title': '18'},
               {'file': 'x42luke_19.html', 'title': '19'},
               {'file': 'x42luke_20.html', 'title': '20'},
               {'file': 'x42luke_21.html', 'title': '21'},
               {'file': 'x42luke_22.html', 'title': '22'},
               {'file': 'x42luke_23.html', 'title': '23'},
               {'file': 'x42luke_24.html', 'title': '24'}],
  'long': 'Luke',
  'short': 'LUK',
  'testament': 'New',
  'tocfile': 'x42luke.html'},
 {'chapters': [{'file': 'John_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x43john_1.html', 'title': '1'},
               {'file': 'x43john_2.html', 'title': '2'},
               {'file': 'x43john_3.html', 'title': '3'},
               {'file': 'x43john_4.html', 'title': '4'},
               {'file': 'x43john_5.html', 'title': '5'},
               {'file': 'x43john_6.html', 'title': '6'},
               {'file': 'x43john_7.html', 'title': '7'},
               {'file': 'x43john_8.html', 'title': '8'},
               {'file': 'x43john_9.html', 'title': '9'},
               {'file': 'x43john_10.html', 'title': '10'},
               {'file': 'x43john_11.html', 'title': '11'},
               {'file': 'x43john_12.html', 'title': '12'},
               {'file': 'x43john_13.html', 'title': '13'},
               {'file': 'x43john_14.html', 'title': '14'},
               {'file': 'x43john_15.html', 'title': '15'},
               {'file': 'x43john_16.html', 'title': '16'},
               {'file': 'x43john_17.html', 'title': '17'},
               {'file': 'x43john_18.html', 'title': '18'},
               {'file': 'x43john_19.html', 'title': '19'},
               {'file': 'x43john_20.html', 'title': '20'},
               {'file': 'x43john_21.html', 'title': '21'}],
  'long': 'John',
  'short': 'JHN',
  'testament': 'New',
  'tocfile': 'x43john.html'},
 {'chapters': [{'file': 'Acts_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x44acts_1.html', 'title': '1'},
               {'file': 'x44acts_2.html', 'title': '2'},
               {'file': 'x44acts_3.html', 'title': '3'},
               {'file': 'x44acts_4.html', 'title': '4'},
               {'file': 'x44acts_5.html', 'title': '5'},
               {'file': 'x44acts_6.html', 'title': '6'},
               {'file': 'x44acts_7.html', 'title': '7'},
               {'file': 'x44acts_8.html', 'title': '8'},
               {'file': 'x44acts_9.html', 'title': '9'},
               {'file': 'x44acts_10.html', 'title': '10'},
               {'file': 'x44acts_11.html', 'title': '11'},
               {'file': 'x44acts_12.html', 'title': '12'},
               {'file': 'x44acts_13.html', 'title': '13'},
               {'file': 'x44acts_14.html', 'title': '14'},
               {'file': 'x44acts_15.html', 'title': '15'},
               {'file': 'x44acts_16.html', 'title': '16'},
               {'file': 'x44acts_17.html', 'title': '17'},
               {'file': 'x44acts_18.html', 'title': '18'},
               {'file': 'x44acts_19.html', 'title': '19'},
               {'file': 'x44acts_20.html', 'title': '20'},
               {'file': 'x44acts_21.html', 'title': '21'},
               {'file': 'x44acts_22.html', 'title': '22'},
               {'file': 'x44acts_23.html', 'title': '23'},
               {'file': 'x44acts_24.html', 'title': '24'},
               {'file': 'x44acts_25.html', 'title': '25'},
               {'file': 'x44acts_26.html', 'title': '26'},
               {'file': 'x44acts_27.html', 'title': '27'},
               {'file': 'x44acts_28.html', 'title': '28'}],
  'long': 'Acts',
  'short': 'ACT',
  'testament': 'New',
  'tocfile': 'x44acts.html'},
 {'chapters': [{'file': 'Rom_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x45romans_1.html', 'title': '1'},
               {'file': 'x45romans_2.html', 'title': '2'},
               {'file': 'x45romans_3.html', 'title': '3'},
               {'file': 'x45romans_4.html', 'title': '4'},
               {'file': 'x45romans_5.html', 'title': '5'},
               {'file': 'x45romans_6.html', 'title': '6'},
               {'file': 'x45romans_7.html', 'title': '7'},
               {'file': 'x45romans_8.html', 'title': '8'},
               {'file': 'x45romans_9.html', 'title': '9'},
               {'file': 'x45romans_10.html', 'title': '10'},
               {'file': 'x45romans_11.html', 'title': '11'},
               {'file': 'x45romans_12.html', 'title': '12'},
               {'file': 'x45romans_13.html', 'title': '13'},
               {'file': 'x45romans_14.html', 'title': '14'},
               {'file': 'x45romans_15.html', 'title': '15'},
               {'file': 'x45romans_16.html', 'title': '16'}],
  'long': 'Romans',
  'short': 'ROM',
  'testament': 'New',
  'tocfile': 'x45romans.html'},
 {'chapters': [{'file': 'ICor_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x461corinthians_1.html', 'title': '1'},
               {'file': 'x461corinthians_2.html', 'title': '2'},
               {'file': 'x461corinthians_3.html', 'title': '3'},
               {'file': 'x461corinthians_4.html', 'title': '4'},
               {'file': 'x461corinthians_5.html', 'title': '5'},
               {'file': 'x461corinthians_6.html', 'title': '6'},
               {'file': 'x461corinthians_7.html', 'title': '7'},
               {'file': 'x461corinthians_8.html', 'title': '8'},
               {'file': 'x461corinthians_9.html', 'title': '9'},
               {'file': 'x461corinthians_10.html', 'title': '10'},
               {'file': 'x461corinthians_11.html', 'title': '11'},
               {'file': 'x461corinthians_12.html', 'title': '12'},
               {'file': 'x461corinthians_13.html', 'title': '13'},
               {'file': 'x461corinthians_14.html', 'title': '14'},
               {'file': 'x461corinthians_15.html', 'title': '15'},
               {'file': 'x461corinthians_16.html', 'title': '16'}],
  'long': '1 Corinthians',
  'short': '1CO',
  'testament': 'New',
  'tocfile': 'x461corinthians.html'},
 {'chapters': [{'file': 'IICor_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x472corinthians_1.html', 'title': '1'},
               {'file': 'x472corinthians_2.html', 'title': '2'},
               {'file': 'x472corinthians_3.html', 'title': '3'},
               {'file': 'x472corinthians_4.html', 'title': '4'},
               {'file': 'x472corinthians_5.html', 'title': '5'},
               {'file': 'x472corinthians_6.html', 'title': '6'},
               {'file': 'x472corinthians_7.html', 'title': '7'},
               {'file': 'x472corinthians_8.html', 'title': '8'},
               {'file': 'x472corinthians_9.html', 'title': '9'},
               {'file': 'x472corinthians_10.html', 'title': '10'},
               {'file': 'x472corinthians_11.html', 'title': '11'},
               {'file': 'x472corinthians_12.html', 'title': '12'},
               {'file': 'x472corinthians_13.html', 'title': '13'}],
  'long': '2 Corinthians',
  'short': '2CO',
  'testament': 'New',
  'tocfile': 'x472corinthians.html'},
 {'chapters': [{'file': 'Gal_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x48galatians_1.html', 'title': '1'},
               {'file': 'x48galatians_2.html', 'title': '2'},
               {'file': 'x48galatians_3.html', 'title': '3'},
               {'file': 'x48galatians_4.html', 'title': '4'},
               {'file': 'x48galatians_5.html', 'title': '5'},
               {'file': 'x48galatians_6.html', 'title': '6'}],
  'long': 'Galatians',
  'short': 'GAL',
  'testament': 'New',
  'tocfile': 'x48galatians.html'},
 {'chapters': [{'file': 'Eph_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x49ephesians_1.html', 'title': '1'},
               {'file': 'x49ephesians_2.html', 'title': '2'},
               {'file': 'x49ephesians_3.html', 'title': '3'},
               {'file': 'x49ephesians_4.html', 'title': '4'},
               {'file': 'x49ephesians_5.html', 'title': '5'},
               {'file': 'x49ephesians_6.html', 'title': '6'}],
  'long': 'Ephesians',
  'short': 'EPH',
  'testament': 'New',
  'tocfile': 'x49ephesians.html'},
 {'chapters': [{'file': 'Phil_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x50philippians_1.html', 'title': '1'},
               {'file': 'x50philippians_2.html', 'title': '2'},
               {'file': 'x50philippians_3.html', 'title': '3'},
               {'file': 'x50philippians_4.html', 'title': '4'}],
  'long': 'Philippians',
  'short': 'PHP',
  'testament': 'New',
  'tocfile': 'x50philippians.html'},
 {'chapters': [{'file': 'Col_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x51colossians_1.html', 'title': '1'},
               {'file': 'x51colossians_2.html', 'title': '2'},
               {'file': 'x51colossians_3.html', 'title': '3'},
               {'file': 'x51colossians_4.html', 'title': '4'}],
  'long': 'Colossians',
  'short': 'COL',
  'testament': 'New',
  'tocfile': 'x51colossians.html'},
 {'chapters': [{'file': 'IThes_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x521thessalonians_1.html', 'title': '1'},
               {'file': 'x521thessalonians_2.html', 'title': '2'},
               {'file': 'x521thessalonians_3.html', 'title': '3'},
               {'file': 'x521thessalonians_4.html', 'title': '4'},
               {'file': 'x521thessalonians_5.html', 'title': '5'}],
  'long': '1 Thessalonians',
  'short': '1TH',
  'testament': 'New',
  'tocfile': 'x521thessalonians.html'},
 {'chapters': [{'file': 'IIThes_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x532thessalonians_1.html', 'title': '1'},
               {'file': 'x532thessalonians_2.html', 'title': '2'},
               {'file': 'x532thessalonians_3.html', 'title': '3'}],
  'long': '2 Thessalonians',
  'short': '2TH',
  'testament': 'New',
  'tocfile': 'x532thessalonians.html'},
 {'chapters': [{'file': 'ITim_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x541timothy_1.html', 'title': '1'},
               {'file': 'x541timothy_2.html', 'title': '2'},
               {'file': 'x541timothy_3.html', 'title': '3'},
               {'file': 'x541timothy_4.html', 'title': '4'},
               {'file': 'x541timothy_5.html', 'title': '5'},
               {'file': 'x541timothy_6.html', 'title': '6'}],
  'long': '1 Timothy',
  'short': '1TI',
  'testament': 'New',
  'tocfile': 'x541timothy.html'},
 {'chapters': [{'file': 'IITim_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x552timothy_1.html', 'title': '1'},
               {'file': 'x552timothy_2.html', 'title': '2'},
               {'file': 'x552timothy_3.html', 'title': '3'},
               {'file': 'x552timothy_4.html', 'title': '4'}],
  'long': '2 Timothy',
  'short': '2TI',
  'testament': 'New',
  'tocfile': 'x552timothy.html'},
 {'chapters': [{'file': 'Titus_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x56titus_1.html', 'title': '1'},
               {'file': 'x56titus_2.html', 'title': '2'},
               {'file': 'x56titus_3.html', 'title': '3'}],
  'long': 'Titus',
  'short': 'TIT',
  'testament': 'New',
  'tocfile': 'x56titus.html'},
 {'chapters': [{'file': 'Phlm_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x57philemon_1.html', 'title': '1'}],
  'long': 'Philemon',
  'short': 'PHM',
  'testament': 'New',
  'tocfile': 'x57philemon.html'},
 {'chapters': [{'file': 'Heb_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x58hebrews_1.html', 'title': '1'},
               {'file': 'x58hebrews_2.html', 'title': '2'},
               {'file': 'x58hebrews_3.html', 'title': '3'},
               {'file': 'x58hebrews_4.html', 'title': '4'},
               {'file': 'x58hebrews_5.html', 'title': '5'},
               {'file': 'x58hebrews_6.html', 'title': '6'},
               {'file': 'x58hebrews_7.html', 'title': '7'},
               {'file': 'x58hebrews_8.html', 'title': '8'},
               {'file': 'x58hebrews_9.html', 'title': '9'},
               {'file': 'x58hebrews_10.html', 'title': '10'},
               {'file': 'x58hebrews_11.html', 'title': '11'},
               {'file': 'x58hebrews_12.html', 'title': '12'},
               {'file': 'x58hebrews_13.html', 'title': '13'}],
  'long': 'Hebrews',
  'short': 'HEB',
  'testament': 'New',
  'tocfile': 'x58hebrews.html'},
 {'chapters': [{'file': 'Jas_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x59james_1.html', 'title': '1'},
               {'file': 'x59james_2.html', 'title': '2'},
               {'file': 'x59james_3.html', 'title': '3'},
               {'file': 'x59james_4.html', 'title': '4'},
               {'file': 'x59james_5.html', 'title': '5'}],
  'long': 'James',
  'short': 'JAS',
  'testament': 'New',
  'tocfile': 'x59james.html'},
 {'chapters': [{'file': 'IPet_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x601peter_1.html', 'title': '1'},
               {'file': 'x601peter_2.html', 'title': '2'},
               {'file': 'x601peter_3.html', 'title': '3'},
               {'file': 'x601peter_4.html', 'title': '4'},
               {'file': 'x601peter_5.html', 'title': '5'}],
  'long': '1 Peter',
  'short': '1PE',
  'testament': 'New',
  'tocfile': 'x601peter.html'},
 {'chapters': [{'file': 'IIPet_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x612peter_1.html', 'title': '1'},
               {'file': 'x612peter_2.html', 'title': '2'},
               {'file': 'x612peter_3.html', 'title': '3'}],
  'long': '2 Peter',
  'short': '2PE',
  'testament': 'New',
  'tocfile': 'x612peter.html'},
 {'chapters': [{'file': 'IJn_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x621john_1.html', 'title': '1'},
               {'file': 'x621john_2.html', 'title': '2'},
               {'file': 'x621john_3.html', 'title': '3'},
               {'file': 'x621john_4.html', 'title': '4'},
               {'file': 'x621john_5.html', 'title': '5'}],
  'long': '1 John',
  'short': '1JN',
  'testament': 'New',
  'tocfile': 'x621john.html'},
 {'chapters': [{'file': 'IIJn_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x632john_1.html', 'title': '1'}],
  'long': '2 John',
  'short': '2JN',
  'testament': 'New',
  'tocfile': 'x632john.html'},
 {'chapters': [{'file': 'IIIJn_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x643john_1.html', 'title': '1'}],
  'long': '3 John',
  'short': '3JN',
  'testament': 'New',
  'tocfile': 'x643john.html'},
 {'chapters': [{'file': 'Jude_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x65jude_1.html', 'title': '1'}],
  'long': 'Jude',
  'short': 'JUD',
  'testament': 'New',
  'tocfile': 'x65jude.html'},
 {'chapters': [{'file': 'Rev_BookIntro_NLT.html', 'title': 'Introduction'},
               {'file': 'x66revelation_1.html', 'title': '1'},
               {'file': 'x66revelation_2.html', 'title': '2'},
               {'file': 'x66revelation_3.html', 'title': '3'},
               {'file': 'x66revelation_4.html', 'title': '4'},
               {'file': 'x66revelation_5.html', 'title': '5'},
               {'file': 'x66revelation_6.html', 'title': '6'},
               {'file': 'x66revelation_7.html', 'title': '7'},
               {'file': 'x66revelation_8.html', 'title': '8'},
               {'file': 'x66revelation_9.html', 'title': '9'},
               {'file': 'x66revelation_10.html', 'title': '10'},
               {'file': 'x66revelation_11.html', 'title': '11'},
               {'file': 'x66revelation_12.html', 'title': '12'},
               {'file': 'x66revelation_13.html', 'title': '13'},
               {'file': 'x66revelation_14.html', 'title': '14'},
               {'file': 'x66revelation_15.html', 'title': '15'},
               {'file': 'x66revelation_16.html', 'title': '16'},
               {'file': 'x66revelation_17.html', 'title': '17'},
               {'file': 'x66revelation_18.html', 'title': '18'},
               {'file': 'x66revelation_19.html', 'title': '19'},
               {'file': 'x66revelation_20.html', 'title': '20'},
               {'file': 'x66revelation_21.html', 'title': '21'},
               {'file': 'x66revelation_22.html', 'title': '22'}],
  'long': 'Revelation',
  'short': 'REV',
  'testament': 'New',
  'tocfile': 'x66revelation.html'}]
