#!/usr/bin/env python3

# requires the rwt_romanized package from the small_python_packages repository.
import argparse
import fileinput
from rwt.romanized import greek,hebrew

parser = argparse.ArgumentParser(description="Convert hebrew or greek romanized text to Unicode.")
parser.add_argument('-l', '--lang', dest='language', default='heb', choices=['heb','grk'], help="Choose the language (default heb)")
parser.add_argument('filenames', metavar='filename', type=str, nargs='*')

args = parser.parse_args()

def to_entity(ch):
    numeric = ord(ch)
    if numeric < 128: return ch
    return ch if numeric < 128 else f'&#x{numeric:04x};'

def process_hebrew(line):
    unicode = hebrew(line)
    print(unicode)
    entities = ''.join(to_entity(ch) for ch in unicode)
    print('{{hebrew text|',entities,'}}', sep='')

def process_greek(line):
    unicode = greek(line)
    print(unicode)
    entities = ''.join(to_entity(ch) for ch in unicode)
    print(entities)

match args.language:
    case 'heb':
        processor = process_hebrew
    case 'grk':
        processor = process_greek

with fileinput.input(args.filenames) as f:
    for line in f:
        processor(line.rstrip())

